# Generated by Django 3.2.25 on 2024-06-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_template', '0005_remove_projecttemplate_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='skip_queue',
            field=models.CharField(default='REQUEUE_FOR_OTHERS', max_length=100),
        ),
    ]
