# Generated by Django 3.1.14 on 2022-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_sfp_inventory', '0003_auto_20220419_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfp',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
