# Generated by Django 3.2.24 on 2024-02-21 13:39

from django.db import migrations, models
import nautobot.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0103_add_db_indexes_to_object_change'),
        ('nautobot_sfp_inventory', '0007_sfp_procurement_ident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfptype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='sfp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sfp',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='sfptype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sfptype',
            name='tags',
            field=nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
