
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-16T04:49:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4626ff71ea49f95b106aae809b54eb23ff1a89a5",
 "version": "1.30.0.post0.dev61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
