from dataclasses import dataclass
from strideutils import stride_requests as stride_requests
from strideutils.stride_config import config as config

@dataclass
class TxResponse:
    stdout: str
    stderr: str
    tx_response: dict | None = ...
    tx_hash: str | None = ...
    success: bool = ...
    raw_log: str | None = ...
    def __init__(self, stdout, stderr, tx_response=..., tx_hash=..., success=..., raw_log=...) -> None: ...

def execute_tx(command: str, api_endpoint: str = ...) -> TxResponse: ...
