import redis
from _typeshed import Incomplete
from strideutils.stride_config import config as config

redis_dbs: Incomplete

def get_redis_db(redis_db_name: str) -> redis.Redis: ...
def get(redis_key: str, db_name: str = 'frontend') -> str | None: ...
def set(redis_key: str, redis_val: str, db_name: str = 'frontend'): ...
def set_keys(dict_to_upload: dict[str, str], db_name: str = 'frontend', prefix: str = ''): ...
