from typing import Literal

APPLICANT_STATUS = Literal[
    "NEW",
    "OPEN",
    "COLLECT_STARTED",
    "COLLECT_COMPLETE",
    "COLLECTED",
    "ANALYZED",
    "CLOSED",
]


RENTAL_FILE_STATUS = Literal[
    "NEW", "OPEN", "COLLECTED", "ANALYZED", "CLOSED", "PROCESSING"
]


RENTAL_FILE_SITUATION = Literal["SINGLE", "COUPLE", "ROOMATES", "SOLID_ROOMATES"]


FILE_STATUS = Literal["RECEIVED", "REJECTED", "PROCESSED", "EXTRACTED"]


DOCUMENT_STATUS = Literal[
    "RECEIVED",
    "PROCESSING",
    "PROCESSED",
    "EXTRACTING",
    "EXTRACTED",
    "VALIDATING",
    "VALIDATED",
    "COLLECTED",
    "ACTION_REQUIRED",
    "APPLICANT_ACTION_REQUIRED",
    "REJECTED",
]

ALERT_STATUS = Literal["SUCCESS", "WARNING", "ERROR", "NEUTRAL"]
