# Generated by Django 3.2.25 on 2024-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_merge_20240702_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='review_status',
            field=models.CharField(choices=[('Reject', 'Reject'), ('Fix', 'Fix'), ('Accept', 'Accept')], max_length=20, null=True),
        ),
    ]
