# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CommandCenter.configuration import Configuration


class ImportUsersFromRemoteDirectory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'users': 'list[str]'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'users': 'users'
    }

    def __init__(self, username=None, password=None, users=None, _configuration=None):  # noqa: E501
        """ImportUsersFromRemoteDirectory - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._username = None
        self._password = None
        self._users = None
        self.discriminator = None

        self.username = username
        self.password = password
        if users is not None:
            self.users = users

    @property
    def username(self):
        """Gets the username of this ImportUsersFromRemoteDirectory.  # noqa: E501

        username of a remote directory user. Zadara doesn't store usernames.  # noqa: E501

        :return: The username of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ImportUsersFromRemoteDirectory.

        username of a remote directory user. Zadara doesn't store usernames.  # noqa: E501

        :param username: The username of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this ImportUsersFromRemoteDirectory.  # noqa: E501

        password of a remote directory user. Zadara doesn't store passwords. Your credentials are only used to authenticate session with your directory.  # noqa: E501

        :return: The password of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ImportUsersFromRemoteDirectory.

        password of a remote directory user. Zadara doesn't store passwords. Your credentials are only used to authenticate session with your directory.  # noqa: E501

        :param password: The password of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def users(self):
        """Gets the users of this ImportUsersFromRemoteDirectory.  # noqa: E501

        array containing usernames of the users to be added  # noqa: E501

        :return: The users of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :rtype: list[str]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this ImportUsersFromRemoteDirectory.

        array containing usernames of the users to be added  # noqa: E501

        :param users: The users of this ImportUsersFromRemoteDirectory.  # noqa: E501
        :type: list[str]
        """

        self._users = users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImportUsersFromRemoteDirectory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImportUsersFromRemoteDirectory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ImportUsersFromRemoteDirectory):
            return True

        return self.to_dict() != other.to_dict()
