# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CommandCenter.configuration import Configuration


class InlineResponse20049ImportedUsers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'firstname': 'str',
        'lastname': 'str',
        'remote_username': 'str'
    }

    attribute_map = {
        'id': 'id',
        'firstname': 'firstname',
        'lastname': 'lastname',
        'remote_username': 'remote_username'
    }

    def __init__(self, id=None, firstname=None, lastname=None, remote_username=None, _configuration=None):  # noqa: E501
        """InlineResponse20049ImportedUsers - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._firstname = None
        self._lastname = None
        self._remote_username = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if firstname is not None:
            self.firstname = firstname
        if lastname is not None:
            self.lastname = lastname
        if remote_username is not None:
            self.remote_username = remote_username

    @property
    def id(self):
        """Gets the id of this InlineResponse20049ImportedUsers.  # noqa: E501


        :return: The id of this InlineResponse20049ImportedUsers.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20049ImportedUsers.


        :param id: The id of this InlineResponse20049ImportedUsers.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def firstname(self):
        """Gets the firstname of this InlineResponse20049ImportedUsers.  # noqa: E501


        :return: The firstname of this InlineResponse20049ImportedUsers.  # noqa: E501
        :rtype: str
        """
        return self._firstname

    @firstname.setter
    def firstname(self, firstname):
        """Sets the firstname of this InlineResponse20049ImportedUsers.


        :param firstname: The firstname of this InlineResponse20049ImportedUsers.  # noqa: E501
        :type: str
        """

        self._firstname = firstname

    @property
    def lastname(self):
        """Gets the lastname of this InlineResponse20049ImportedUsers.  # noqa: E501


        :return: The lastname of this InlineResponse20049ImportedUsers.  # noqa: E501
        :rtype: str
        """
        return self._lastname

    @lastname.setter
    def lastname(self, lastname):
        """Sets the lastname of this InlineResponse20049ImportedUsers.


        :param lastname: The lastname of this InlineResponse20049ImportedUsers.  # noqa: E501
        :type: str
        """

        self._lastname = lastname

    @property
    def remote_username(self):
        """Gets the remote_username of this InlineResponse20049ImportedUsers.  # noqa: E501


        :return: The remote_username of this InlineResponse20049ImportedUsers.  # noqa: E501
        :rtype: str
        """
        return self._remote_username

    @remote_username.setter
    def remote_username(self, remote_username):
        """Sets the remote_username of this InlineResponse20049ImportedUsers.


        :param remote_username: The remote_username of this InlineResponse20049ImportedUsers.  # noqa: E501
        :type: str
        """

        self._remote_username = remote_username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20049ImportedUsers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20049ImportedUsers):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20049ImportedUsers):
            return True

        return self.to_dict() != other.to_dict()
