# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CommandCenter.configuration import Configuration


class InlineResponse20055ZsnapSettingsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'server': 'str',
        'user': 'str',
        'max_allowed_mb': 'int',
        'max_retain_mb': 'int'
    }

    attribute_map = {
        'server': 'server',
        'user': 'user',
        'max_allowed_mb': 'max_allowed_mb',
        'max_retain_mb': 'max_retain_mb'
    }

    def __init__(self, server=None, user=None, max_allowed_mb=None, max_retain_mb=None, _configuration=None):  # noqa: E501
        """InlineResponse20055ZsnapSettingsData - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._server = None
        self._user = None
        self._max_allowed_mb = None
        self._max_retain_mb = None
        self.discriminator = None

        if server is not None:
            self.server = server
        if user is not None:
            self.user = user
        if max_allowed_mb is not None:
            self.max_allowed_mb = max_allowed_mb
        if max_retain_mb is not None:
            self.max_retain_mb = max_retain_mb

    @property
    def server(self):
        """Gets the server of this InlineResponse20055ZsnapSettingsData.  # noqa: E501


        :return: The server of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :rtype: str
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this InlineResponse20055ZsnapSettingsData.


        :param server: The server of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :type: str
        """

        self._server = server

    @property
    def user(self):
        """Gets the user of this InlineResponse20055ZsnapSettingsData.  # noqa: E501


        :return: The user of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this InlineResponse20055ZsnapSettingsData.


        :param user: The user of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def max_allowed_mb(self):
        """Gets the max_allowed_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501


        :return: The max_allowed_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :rtype: int
        """
        return self._max_allowed_mb

    @max_allowed_mb.setter
    def max_allowed_mb(self, max_allowed_mb):
        """Sets the max_allowed_mb of this InlineResponse20055ZsnapSettingsData.


        :param max_allowed_mb: The max_allowed_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :type: int
        """

        self._max_allowed_mb = max_allowed_mb

    @property
    def max_retain_mb(self):
        """Gets the max_retain_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501


        :return: The max_retain_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :rtype: int
        """
        return self._max_retain_mb

    @max_retain_mb.setter
    def max_retain_mb(self, max_retain_mb):
        """Sets the max_retain_mb of this InlineResponse20055ZsnapSettingsData.


        :param max_retain_mb: The max_retain_mb of this InlineResponse20055ZsnapSettingsData.  # noqa: E501
        :type: int
        """

        self._max_retain_mb = max_retain_mb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20055ZsnapSettingsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20055ZsnapSettingsData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20055ZsnapSettingsData):
            return True

        return self.to_dict() != other.to_dict()
