# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from CommandCenter.configuration import Configuration


class MaintenanceMode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enter_maintenance_mode': 'bool'
    }

    attribute_map = {
        'enter_maintenance_mode': 'enter_maintenance_mode'
    }

    def __init__(self, enter_maintenance_mode=None, _configuration=None):  # noqa: E501
        """MaintenanceMode - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._enter_maintenance_mode = None
        self.discriminator = None

        if enter_maintenance_mode is not None:
            self.enter_maintenance_mode = enter_maintenance_mode

    @property
    def enter_maintenance_mode(self):
        """Gets the enter_maintenance_mode of this MaintenanceMode.  # noqa: E501

        Enter VPSA Object Storage into maintenance mode. Set to false or omit to exit from maintenance mode.  # noqa: E501

        :return: The enter_maintenance_mode of this MaintenanceMode.  # noqa: E501
        :rtype: bool
        """
        return self._enter_maintenance_mode

    @enter_maintenance_mode.setter
    def enter_maintenance_mode(self, enter_maintenance_mode):
        """Sets the enter_maintenance_mode of this MaintenanceMode.

        Enter VPSA Object Storage into maintenance mode. Set to false or omit to exit from maintenance mode.  # noqa: E501

        :param enter_maintenance_mode: The enter_maintenance_mode of this MaintenanceMode.  # noqa: E501
        :type: bool
        """

        self._enter_maintenance_mode = enter_maintenance_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MaintenanceMode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaintenanceMode):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MaintenanceMode):
            return True

        return self.to_dict() != other.to_dict()
