def identify_service(port):
    services = {
        1: "TCP Port Service Multiplexer (TCPMUX)",
        5: "RJE (Remote Job Entry)",
        7: "Echo Protocol",
        9: "Discard Protocol",
        11: "SYSTAT",
        13: "Daytime Protocol",
        17: "Quote of the Day (QOTD)",
        19: "Chargen (Character Generator Protocol)",
        21: "FTP (File Transfer Protocol)",
        22: "SSH (Secure Shell)",
        23: "Telnet",
        25: "SMTP (Simple Mail Transfer Protocol)",
        37: "Time Protocol",
        39: "Resource Location Protocol (RLP)",
        43: "WHOIS",
        53: "DNS (Domain Name System)",
        67: "DHCP (Dynamic Host Configuration Protocol)",
        68: "DHCP Client",
        69: "TFTP (Trivial File Transfer Protocol)",
        70: "Gopher Protocol",
        79: "Finger Protocol",
        80: "HTTP (Hypertext Transfer Protocol)",
        81: "HTTP (Alternative)",
        82: "HTTP (Alternative)",
        83: "MIT ML Device",
        84: "CTI (Computer Telephony Integration)",
        85: "MIT ML Device",
        88: "Kerberos",
        90: "Network News Transfer Protocol (NNTP)",
        110: "POP3 (Post Office Protocol)",
        115: "SFTP (Simple File Transfer Protocol)",
        119: "Network News Transfer Protocol (NNTP)",
        123: "NTP (Network Time Protocol)",
        135: "MS DCOM Service Control Manager",
        137: "NetBIOS Name Service",
        138: "NetBIOS Datagram Service",
        139: "NetBIOS Session Service",
        143: "IMAP (Internet Message Access Protocol)",
        161: "SNMP (Simple Network Management Protocol)",
        162: "SNMP Trap",
        179: "BGP (Border Gateway Protocol)",
        194: "IRC (Internet Relay Chat)",
        443: "HTTPS (HTTP Secure)",
        465: "SMTPS (SMTP Secure)",
        514: "Syslog",
        520: "RIP (Routing Information Protocol)",
        521: "RIPng",
        543: "Klogin (Kerberos Login)",
        544: "Kshell (Kerberos Shell)",
        563: "NNTPS (NNTP Secure)",
        587: "SMTP (Secure)",
        593: "DCE RPC",
        636: "LDAPS (LDAP over SSL)",
        993: "IMAPS (Internet Message Access Protocol Secure)",
        995: "POP3S (POP3 Secure)",
        3306: "MySQL Database",
        3389: "RDP (Remote Desktop Protocol)",
        5432: "PostgreSQL Database",
        5900: "VNC (Virtual Network Computing)",
        6379: "Redis Database",
        8080: "HTTP (Alternative)",
        8888: "HTTP (Alternative)",
        10000: "Webmin",
        27017: "MongoDB",
        50000: "Oracle DB",
        54321: "NetBIOS (Windows SMB)",
        49152: "Dynamic/Private Ports (also used by many applications)",
        49153: "UPnP (Universal Plug and Play)",
        49154: "UPnP (Universal Plug and Play)",
        49155: "UPnP (Universal Plug and Play)",
        49156: "UPnP (Universal Plug and Play)",
        49157: "UPnP (Universal Plug and Play)",
        3000: "Node.js Application",
        5001: "Common for web applications",
        5002: "Common for web applications",
        5003: "Common for web applications",
        6001: "X11 (X Window System)",
        6002: "X11 (X Window System)",
        8000: "HTTP (Alternative)",
        8081: "HTTP (Alternative)",
        8082: "HTTP (Alternative)",
        8443: "HTTPS (Alternative)",
        9000: "PHP Development Server",
        9001: "Common for web applications",
        9443: "HTTPS (Alternative)",
        10001: "Common for web applications",
        11000: "Common for web applications",
        15000: "Common for web applications",
        20000: "Common for web applications",
        30000: "Common for web applications",
        50000: "RMI (Remote Method Invocation)",
        55000: "SSL (Secure Socket Layer)",
        60000: "SSL (Secure Socket Layer)",
        70000: "SSL (Secure Socket Layer)",
        32768: "Dynamic/Private Ports",
        49152: "Dynamic/Private Ports",
        49153: "UPnP (Universal Plug and Play)",
        49154: "UPnP (Universal Plug and Play)",
        49155: "UPnP (Universal Plug and Play)",
        49156: "UPnP (Universal Plug and Play)",
        49157: "UPnP (Universal Plug and Play)",
        40000: "Common for web applications",
        45000: "Common for web applications",
        42000: "Common for web applications",
        50050: "Common for web applications",
        8088: "HTTP (Alternative)",
        8089: "HTTP (Alternative)",
        49151: "Common for web applications",
    }
    return services.get(port, "Unknown Service")
