# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_month.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65num_month.proto*\xf8\x01\n\tEnumMonth\x12\x11\n\rMONTH_UNKNOWN\x10\x00\x12\x11\n\rMONTH_JANUARY\x10\x01\x12\x12\n\x0eMONTH_FEBRUARY\x10\x02\x12\x0f\n\x0bMONTH_MARCH\x10\x03\x12\x0f\n\x0bMONTH_APRIL\x10\x04\x12\r\n\tMONTH_MAY\x10\x05\x12\x0e\n\nMONTH_JUNE\x10\x06\x12\x0e\n\nMONTH_JULY\x10\x07\x12\x10\n\x0cMONTH_AUGUST\x10\x08\x12\x13\n\x0fMONTH_SEPTEMBER\x10\t\x12\x11\n\rMONTH_OCTOBER\x10\n\x12\x12\n\x0eMONTH_NOVEMBER\x10\x0b\x12\x12\n\x0eMONTH_DECEMBER\x10\x0c\x42\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_month_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _globals['_ENUMMONTH']._serialized_start=21
  _globals['_ENUMMONTH']._serialized_end=269
# @@protoc_insertion_point(module_scope)
