# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signalr_one_hub_event_payload.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import signalr_one_hub_dataset_event_pb2 as signalr__one__hub__dataset__event__pb2
from . import key_value_pb2 as key__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#signalr_one_hub_event_payload.proto\x1a#signalr_one_hub_dataset_event.proto\x1a\x0fkey_value.proto\"{\n\x19SignalROneHubEventPayload\x12\x1f\n\tkeyValues\x18\x01 \x01(\x0b\x32\n.KeyValuesH\x00\x12\x32\n\x0c\x64\x61tasetEvent\x18\x02 \x01(\x0b\x32\x1a.SignalROneHubDatasetEventH\x00\x42\t\n\x07\x63ontentB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signalr_one_hub_event_payload_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _globals['_SIGNALRONEHUBEVENTPAYLOAD']._serialized_start=93
  _globals['_SIGNALRONEHUBEVENTPAYLOAD']._serialized_end=216
# @@protoc_insertion_point(module_scope)
