# Generated by Django 3.2.25 on 2024-06-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0033_remove_project_compressed_thumbnail_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Data of layout parameters of dashboard widgets', verbose_name='data')),
                ('project', models.ForeignKey(help_text='Project ID for dashboard', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_dashboard', to='projects.project')),
            ],
        ),
    ]
