# Generated by Django 3.2.25 on 2024-06-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_remove_project_compressed_thumbnail_images'),
        ('project_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdashboard',
            name='data',
        ),
        migrations.AddField(
            model_name='projectdashboard',
            name='overview_layout',
            field=models.JSONField(default=list, help_text='Data of layout parameters of overview of project dashboard.', verbose_name='Overview Layout'),
        ),
        migrations.AddField(
            model_name='projectdashboard',
            name='performance_layout',
            field=models.JSONField(default=list, help_text='Data of layout parameters of performance part of dashboard.', verbose_name='Performance Layout'),
        ),
        migrations.AlterField(
            model_name='projectdashboard',
            name='project',
            field=models.OneToOneField(help_text='Project ID for dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='project_dashboard', to='projects.project'),
        ),
    ]
