# Generated by Django 3.2.25 on 2024-07-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_project_require_comments_on_skip'),
        ('projects', '0036_auto_20240708_0625'),
    ]

    operations = [
    ]
