# Generated by Django 3.2.25 on 2024-05-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspaces_organization'),
        ('projects', '0027_auto_20240510_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspace.workspaces'),
        ),
    ]
