from enum import Enum


class StakeRegistrationDetailType(str, Enum):
    AUTH_COMMITTEE_HOT_CERT = "AUTH_COMMITTEE_HOT_CERT"
    GENESIS_KEY_DELEGATION = "GENESIS_KEY_DELEGATION"
    MOVE_INSTATENEOUS_REWARDS_CERT = "MOVE_INSTATENEOUS_REWARDS_CERT"
    POOL_REGISTRATION = "POOL_REGISTRATION"
    POOL_RETIREMENT = "POOL_RETIREMENT"
    REG_CERT = "REG_CERT"
    REG_DREP_CERT = "REG_DREP_CERT"
    RESIGN_COMMITTEE_COLD_CERT = "RESIGN_COMMITTEE_COLD_CERT"
    STAKE_DELEGATION = "STAKE_DELEGATION"
    STAKE_DEREGISTRATION = "STAKE_DEREGISTRATION"
    STAKE_REGISTRATION = "STAKE_REGISTRATION"
    STAKE_REG_DELEG_CERT = "STAKE_REG_DELEG_CERT"
    STAKE_VOTE_DELEG_CERT = "STAKE_VOTE_DELEG_CERT"
    STAKE_VOTE_REG_DELEG_CERT = "STAKE_VOTE_REG_DELEG_CERT"
    UNREG_CERT = "UNREG_CERT"
    UNREG_DREP_CERT = "UNREG_DREP_CERT"
    UPDATE_DREP_CERT = "UPDATE_DREP_CERT"
    VOTE_DELEG_CERT = "VOTE_DELEG_CERT"
    VOTE_REG_DELEG_CERT = "VOTE_REG_DELEG_CERT"

    def __str__(self) -> str:
        return str(self.value)
