from enum import Enum

class RetCode(Enum):
    OK = 'ok'
    ERROR = 'error'

class Granularity(Enum):
    HOURLY = 'hourly'
    DAILY = 'daily'

APPLE_COUNTRIES = 'AE,AF,AG,AI,AL,AM,AO,AR,AT,AU,AZ,BA,BB,BE,BF,BG,BH,BJ,BM,BN,BO,BR,BS,BT,BW,BY,BZ,CA,CD,CG,CH,CI,CL,CM,CN,CO,CR,CV,CY,CZ,DE,DK,DM,DO,DZ,EC,EE,EG,ES,FI,FJ,FM,FR,GA,GB,GD,GE,GH,GM,GR,GT,GW,GY,HK,HN,HR,HU,ID,IE,IL,IN,IQ,IS,IT,JM,JO,JP,KE,KG,KH,KN,KR,KW,KY,KZ,LA,LB,LC,LK,LR,LT,LU,LV,LY,MA,MD,ME,MG,MK,ML,MM,MN,MO,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NE,NG,NI,NL,NO,NP,NR,NZ,OM,PA,PE,PG,PH,PK,PL,PT,PW,PY,QA,RO,RS,RU,RW,SA,SB,SC,SE,SG,SI,SK,SL,SN,SR,ST,SV,SZ,TC,TD,TH,TJ,TM,TN,TO,TR,TT,TW,TZ,UA,UG,US,UY,UZ,VC,VE,VG,VN,VU,XK,YE,ZA,ZM,ZW'
DATE_FMT = '%Y-%m-%d'