# Generated by Django 3.2.25 on 2024-07-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_alter_review_reviewer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='task_review_task_id_7196ff_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='annotation',
            field=models.ForeignKey(blank=True, help_text='Annotation being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.annotation'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['annotation'], name='task_review_annotat_568deb_idx'),
        ),
    ]
