# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accinfo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccinfo.proto\x12\tdragonbot\"\x81\x01\n\x07\x41\x63\x63Info\x12\r\n\x05power\x18\x01 \x01(\x02\x12\x17\n\x0fmax_power_short\x18\x02 \x01(\x02\x12\x16\n\x0enet_cash_power\x18\x03 \x01(\x02\x12\x14\n\x0ctotal_assets\x18\x04 \x01(\x02\x12\x0c\n\x04\x63\x61sh\x18\x05 \x01(\x02\x12\x12\n\nmarket_val\x18\x06 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accinfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCINFO']._serialized_start=29
  _globals['_ACCINFO']._serialized_end=158
# @@protoc_insertion_point(module_scope)
