# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20020_comments_comment import InlineResponse20020CommentsComment  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20020CommentsComment(unittest.TestCase):
    """InlineResponse20020CommentsComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20020CommentsComment(self):
        """Test InlineResponse20020CommentsComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20020_comments_comment.InlineResponse20020CommentsComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
