# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.allocate_vlan_to_cloud_user import AllocateVlanToCloudUser  # noqa: E501
from CommandCenter.rest import ApiException


class TestAllocateVlanToCloudUser(unittest.TestCase):
    """AllocateVlanToCloudUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocateVlanToCloudUser(self):
        """Test AllocateVlanToCloudUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.allocate_vlan_to_cloud_user.AllocateVlanToCloudUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
