# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.delete_address_from_remote_rsyslog_server_list import DeleteAddressFromRemoteRsyslogServerList  # noqa: E501
from CommandCenter.rest import ApiException


class TestDeleteAddressFromRemoteRsyslogServerList(unittest.TestCase):
    """DeleteAddressFromRemoteRsyslogServerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteAddressFromRemoteRsyslogServerList(self):
        """Test DeleteAddressFromRemoteRsyslogServerList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.delete_address_from_remote_rsyslog_server_list.DeleteAddressFromRemoteRsyslogServerList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
