# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200131 import InlineResponse200131  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200131(unittest.TestCase):
    """InlineResponse200131 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200131(self):
        """Test InlineResponse200131"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200131.InlineResponse200131()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
