# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20044 import InlineResponse20044  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20044(unittest.TestCase):
    """InlineResponse20044 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20044(self):
        """Test InlineResponse20044"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20044.InlineResponse20044()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
