# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.api.images_api import ImagesApi  # noqa: E501
from CommandCenter.rest import ApiException


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self):
        self.api = CommandCenter.api.images_api.ImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_images(self):
        """Test case for get_all_images

        """
        pass

    def test_get_image(self):
        """Test case for get_image

        """
        pass

    def test_remove_recommended(self):
        """Test case for remove_recommended

        """
        pass

    def test_set_default_image(self):
        """Test case for set_default_image

        """
        pass

    def test_set_recommended(self):
        """Test case for set_recommended

        """
        pass


if __name__ == '__main__':
    unittest.main()
