# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.reboot_storage_node import RebootStorageNode  # noqa: E501
from CommandCenter.rest import ApiException


class TestRebootStorageNode(unittest.TestCase):
    """RebootStorageNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRebootStorageNode(self):
        """Test RebootStorageNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.reboot_storage_node.RebootStorageNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
