# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200103_capacity_trend import InlineResponse200103CapacityTrend  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200103CapacityTrend(unittest.TestCase):
    """InlineResponse200103CapacityTrend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200103CapacityTrend(self):
        """Test InlineResponse200103CapacityTrend"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200103_capacity_trend.InlineResponse200103CapacityTrend()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
