# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.add_drives_to_zios import AddDrivesToZios  # noqa: E501
from CommandCenter.rest import ApiException


class TestAddDrivesToZios(unittest.TestCase):
    """AddDrivesToZios unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddDrivesToZios(self):
        """Test AddDrivesToZios"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.add_drives_to_zios.AddDrivesToZios()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
