# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09-sp2
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20017_custom_network import InlineResponse20017CustomNetwork  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20017CustomNetwork(unittest.TestCase):
    """InlineResponse20017CustomNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017CustomNetwork(self):
        """Test InlineResponse20017CustomNetwork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20017_custom_network.InlineResponse20017CustomNetwork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
