# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_delphi_model_mode.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65num_delphi_model_mode.proto*O\n\x13\x45numDelphiModelMode\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Nowcast\x10\x01\x12\x0c\n\x08\x46orecast\x10\x02\x12\x10\n\x0cOptimization\x10\x03\x42\x1d\xaa\x02\x1aONE.Models.CSharp.Externalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enum_delphi_model_mode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\032ONE.Models.CSharp.External'
  _globals['_ENUMDELPHIMODELMODE']._serialized_start=32
  _globals['_ENUMDELPHIMODELMODE']._serialized_end=111
# @@protoc_insertion_point(module_scope)
