# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_context.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enum_time_context_pb2 as enum__time__context__pb2
import enum_timezone_pb2 as enum__timezone__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12time_context.proto\x1a\x17\x65num_time_context.proto\x1a\x13\x65num_timezone.proto\"U\n\x0bTimeContext\x12%\n\x0b\x63ontextType\x18\x01 \x01(\x0e\x32\x10.EnumTimeContext\x12\x1f\n\x08timezone\x18\x02 \x01(\x0e\x32\r.EnumTimeZoneB\x14\xaa\x02\x11ONE.Models.CSharpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_context_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021ONE.Models.CSharp'
  _globals['_TIMECONTEXT']._serialized_start=68
  _globals['_TIMECONTEXT']._serialized_end=153
# @@protoc_insertion_point(module_scope)
