
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-17T16:39:58+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "544c46679d15c0d0f3752528313eb8050cc78a3e",
 "version": "0.10.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
